# -*- coding: utf-8 -*-
import base64

# Form implementation generated from reading ui file 'llm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

from src import icons

class Ui_LLM(object):
    def setupUi(self, LLM):
        LLM.setObjectName("LLM")
        LLM.resize(618, 560)
        icon = QIcon()
        icon.addPixmap(QtGui.QPixmap.fromImage(QtGui.QImage.fromData(base64.b64decode(icons.flower))))
        self.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LLM)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialog = QtWidgets.QTextEdit(LLM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.dialog.setFont(font)
        self.dialog.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dialog.setObjectName("dialog")
        self.verticalLayout_2.addWidget(self.dialog)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.msg_text = QtWidgets.QLineEdit(LLM)
        self.msg_text.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.msg_text.setFont(font)
        self.msg_text.setObjectName("msg_text")
        self.msg_text.setPlaceholderText("输入你的消息...")
        self.horizontalLayout.addWidget(self.msg_text)
        self.msg_send = QtWidgets.QPushButton(LLM)
        self.msg_send.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        self.msg_send.setFont(font)
        self.msg_send.setObjectName("msg_send")
        self.horizontalLayout.addWidget(self.msg_send)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(LLM)
        QtCore.QMetaObject.connectSlotsByName(LLM)

    def retranslateUi(self, LLM):
        _translate = QtCore.QCoreApplication.translate
        LLM.setWindowTitle(_translate("LLM", "智能助手"))
        self.msg_send.setText(_translate("LLM", "发送"))
